### ISSUE TITLE
Scrape useful layers from map.utoronto.ca 

### ISSUE THREAD

**Issue by qasim** [cobalt-uoft/uoft-scrapers#20]
Check out http://map.utoronto.ca/ and how there are so many layers. If any of the layers make sense, let's build a scraper for them.

**Comment by kashav** [comment]
Started a [LayersScraper](https://github.com/kshvmdn/uoft-scrapers/blob/master/uoftscrapers/scrapers/layers/__init__.py#L6) subclass for all layers' scrapers. Don't know if this is even required, but it seems like scraping each layer is gonna be done similarly. 

Also, does it make sense to add this alongside the [Scraper](https://github.com/cobalt-uoft/uoft-scrapers/blob/master/uoftscrapers/scrapers/scraper/__init__.py#L5) superclass? (not really sure if this is the Pythonic way of doing things)

**Comment by qasim** [comment]
It's a good idea; lots of duplicate code otherwise.

In terms of where to place it, not too sure either. Since its a very basic superclass, we can move `scrapers/layers/` to `scrapers/scraper/layers/`. That way the root directories in `scrapers/` will have the `scraper/` where all the superclasses are, and the rest of the folders are actually the real scrapers.

**Comment by qasim** [comment]
Some other layers we should consider:
- Washrooms
- Wireless access points
- Parking lots
- Bicycle racks
- Building entrances (accessibility)

**Comment by qasim** [comment]
Everything I'd like to see for now from layers has its own issue. Closing this, but will reference it when we decide to go for more.
