### ISSUE TITLE
Add a table of contents to README.md

### ISSUE THREAD

**Issue by qasim** [cobalt-uoft/uoft-scrapers#22]
It's getting hard to read the reference, a TOC for all the classes seems like a good idea

**Comment by malligaraj** [comment]
Hi! @qasim I am new to contributing to OSS and I think this could be a great way to get in my first pull request if you are okay with it :)

**Comment by qasim** [comment]
@malligaraj hello! Welcome to open source. I'll assign this to you, let me know if you have any questions.
