### ISSUE TITLE
Library information scraper

### ISSUE THREAD

**Issue by qasim** [cobalt-uoft/uoft-scrapers#31]
https://onesearch.library.utoronto.ca/visit

Most libraries at UofT aren't whole buildings, here's a list of libraries that /are/ buildings but also inside other buildings.

Library names, location (we'd have to map these to building IDs to minimize duplicate information), operating hours, photo, website URL, description, "collection strengths", and "how to access".

**Comment by g3wanghc** [comment]
@qasim I'm down to work on this one.

**Comment by qasim** [comment]
It's yours!

**Comment by g3wanghc** [comment]
Invite me to cobalt? :V

**Comment by g3wanghc** [comment]
Just had a chance to take a look at the actual site. `All hours`, `Collection strengths` and `How to access` are optional fields that may not exist. `All hours` is actually a link to a calendar, should we just provide the link? 

@qasim Do we have a public API key without rate-limiting for `GET buildings/search/?q={{address}}&key={{public_key}}`?

**Comment by g3wanghc** [comment]
Libraries have 2 links. e.g. "Health Science Information Consortium of Toronto"

`/content/health-science-information-consortium-toronto`
`/library-info/HSICT`

And don't necessarily have a `Description`, and sometimes would contain a `Teaser text`.

**Comment by qasim** [comment]
We have no way of requesting API for scrapers yet. It's on the roadmap though.

On average is there enough information? If not, we may just call it here and not scrape libraries.

As for hours, I saw that they had the link to the calendar. If we do continue to scrape, we could do 1 week of the calendar and have similar hours structure as the Food scraper does

**Comment by g3wanghc** [comment]
On average, there's usually enough information. 

I will take your advice on the calendar thing. It doesn't look like too much work. ¯_(ツ)_/¯
