### ISSUE TITLE
UTM athletics scraper

### ISSUE THREAD

**Issue by qasim** [cobalt-uoft/uoft-scrapers#34]
https://m.utm.utoronto.ca/physed.php

Scrape everything that shows up on that page.

In the meanwhile, I will try and get in contact with UTSG athletics to see if they can give their internal drop-in calendar to the public (I know it exists! I've seen it!).

As for UTSC, anyone from there can help out if they know any information about UTSC athletics.

**Comment by qasim** [comment]
Proposed schema (for each type of athletics):

``` js
{
  "id": String,
  "name": String,
  "location": String,
  "building_id": String,
  "date": String,
  "start_time": String,
  "end_time": String
}
```

**Comment by kashav** [comment]
Started working on [this](https://github.com/kshvmdn/uoft-scrapers/blob/utm-athletics/uoftscrapers/scrapers/athletics/utm/__init__.py), scrapes all events for the given month.

Here's the current schema:

``` js
{
  "date": String,
  "events": [{
    "title": String,
    "location": String,
    "start_time": String,
    "end_time": String,
  }]
}
```

This one may work as well (using event titles as IDs):

``` js
{
  "id": String,
  "sessions": [{
    "location": String,
    "date": String,
    "start_time": String,
    "end_time": String
  }]
}
```

As far as I can tell, all athletic events happen in the same building, the Recreation, Athletic & Wellness Centre (building `332`). Does it make sense to include a `building_id` key if it's the same for all of them?

**Comment by qasim** [comment]
@kshvmdn we can leave `building_id` in for now in anticipation for using this same schema for UTSG/UTSC data.

We can go with the former schema to match how our data looks for shuttles. LGTM!

**Comment by qasim** [comment]
@kshvmdn  I merged a few refactors / small overhaul of scraper layout, let me know if you're able to merge master properly.

**Comment by kashav** [comment]
@qasim No conflicts – I think it's good to go! 

https://github.com/cobalt-uoft/uoft-scrapers/pull/51

**Comment by qasim** [comment]
UTSC scraper, awesome!

Let's hope UTSG gives us standardized info on their stuff soon.
