### ISSUE TITLE
Events scraper

### ISSUE THREAD

**Issue by qasim** [cobalt-uoft/uoft-scrapers#36]
https://www.events.utoronto.ca/

**Comment by qasim** [comment]
Proposed schema:

``` js
{
  "id": String,
  "title": String,
  "date": {
    "start": String,
    "end": String,
  },
  "url": String,
  "description": String,
  "campus": String,
  "address": String,
  "audience": [String]
}
```

**Comment by g3wanghc** [comment]
@qasim I'm down to work it. :V

**Comment by qasim** [comment]
@g3wanghc Awesome. Here's a little tweaked schema that I had in mind, keeping with conventions from other scrapers:

``` js
{
  "id": String,
  "title": String,
  "date": String,
  "start_time": String,
  "end_time": String
  "url": String,
  "description": String,
  "campus": String,
  "address": String,
  "audience": [String]
}
```

`date` would be ISO 8601 format like `2016-04-15`.
`start_time` and `end_time` would also be ISO 8601 like `2016-04-15T12:00:00-04:00` (standardized for eastern timezone).
`url` would just be the URL of the event posting, i.e. https://www.events.utoronto.ca/index.php?action=singleView&eventid=12052.

My thinking is each scraper run should go through all the pages of events (so every event currently listed) and then open each link inside to grab the more detailed information to complete the schema.

Let me know what you think!

**Comment by g3wanghc** [comment]
Sure, looks like fun. :+1:

**Comment by g3wanghc** [comment]
@qasim Do we care about Admission Price, Contact Info, Website and Event Sponsor?
