### ISSUE TITLE
scraper.get() 404 limbo

### ISSUE THREAD

**Issue by g3wanghc** [cobalt-uoft/uoft-scrapers#62]
Scraper.get('http://www.asc.utoronto.ca/Hours---Location.htm') limbos after first attempt with 404 response.

**Comment by g3wanghc** [comment]
Non `200 status_code` should increment `attempts`.

**Comment by g3wanghc** [comment]
Oh nvm this was fixed. Will do a pull. :|

**Comment by arkon** [comment]
@g3wanghc Is it still happening?

**Comment by g3wanghc** [comment]
@arkon Fixed it in my branch. Will make a pull request today.

**Comment by g3wanghc** [comment]
Adding `requests.exceptions.InvalidSchema` as exception.

**Comment by g3wanghc** [comment]
This issue should be fixed with pull request #63.
