### ISSUE TITLE
Change all times (that don't have specific days attached to them) to seconds since midnight

### ISSUE THREAD

**Issue by qasim** [cobalt-uoft/uoft-scrapers#64]
This includes courses and food, I believe.

Events should be updated so that the times are ISO 8601 if they aren't already.

**Comment by g3wanghc** [comment]
@qasim I will fix start-time and end-time for `Events`. I've just noticed that there's a bug with the am/pm.

**Comment by kashav** [comment]
I'll take food and courses! https://github.com/kshvmdn/uoft-scrapers/tree/change-hours
