### ISSUE TITLE
Outstanding times which should be converted to seconds since midnight

### ISSUE THREAD

**Issue by qasim** [cobalt-uoft/uoft-scrapers#70]
- [x] Exams #71
  - [x] `start_time`
  - [x] `end_time`
  - [x] add `duration` key
- [x] Athletics #68 
  - [x] `start_time`
  - [x] `end_time`
  - [x] add `duration` key
- [x] Shuttles #69 
  - [x] `routes.stops.times.time`
- [x] Events #67 #72
  - [x] `start_time`
  - [x] `end_time`
  - [x] add `duration` key

**Comment by qasim** [comment]
We'll ship a new `uoft-scrapers@0.6.0` once all these are checked. (at that point I can update all the datasets and we can start working on fixing up cobalt-uoft/cobalt)

**Comment by kashav** [comment]
Exams ✔️ 

https://github.com/cobalt-uoft/uoft-scrapers/pull/71

**Comment by kashav** [comment]
Events ✔️ 

https://github.com/cobalt-uoft/uoft-scrapers/pull/72

**Comment by qasim** [comment]
Boom
