### ISSUE TITLE
Change Courses (coursefinder) scraper from hours since midnight to seconds since midnight

### ISSUE THREAD

**Issue by qasim** [cobalt-uoft/uoft-scrapers#76]
The courses schema still scrapes and returns times in the "hours since midnight" form. Should be changed to seconds since midnight to match all the other scrapers.

**Comment by kashav** [comment]
@qasim I think this is [done](https://github.com/cobalt-uoft/uoft-scrapers/blob/master/uoftscrapers/scrapers/courses/__init__.py#L200), courses [dataset](https://github.com/cobalt-uoft/datasets/commit/6d2bd6bb282ab4651e53978ce12a444123bad917) might need an update.

**Comment by qasim** [comment]
I probably should have checked first, huh. Thanks!
