### ISSUE TITLE
Architecture exams scraper

### ISSUE THREAD

**Issue by arkon** [cobalt-uoft/uoft-scrapers#78]
Seems like Daniels has [their own list of exams](https://www.daniels.utoronto.ca/node/5346) too

**Comment by arkon** [comment]
On a semi-related noted, some other faculties (e.g. law and pharmacy) also have their own exam schedules, but I only found PDFs of them.

**Comment by kashav** [comment]
Scraping Daniels shouldn't be hard, not too sure about the PDFs.

I think something to consider is that none of these faculties have courses on CourseFinder, which means they're not in the courses API. Does it still make sense to build scrapers for them?

UofT only provides [links](http://life.utoronto.ca/get-info/important-dates/#Exam%20Timetables) to the schedules for the four faculties that we already support.

> All other students should check with their faculty registrar for up to date information regarding exam schedules.

Maybe we should do the same? 😛

**Comment by qasim** [comment]
+1 not supporting them, for now at least. If they were in CourseFinder I'd think differently.

**Comment by qasim** [comment]
Worth noting that Architecture / law / pharmacy / etc. aren't supported in the new UTSG timetable either (since I guess it's only for A&S).
