### ISSUE TITLE
Make all code within this repository comply with PEP8

### ISSUE THREAD

**Issue by qasim** [cobalt-uoft/uoft-scrapers#8]
There may be a possibility of using some cool pre-commit hooks to check PEP8 compliance. Otherwise, we should begin moving the written code to PEP8 standards while then maintaining it as such too.

**Comment by g3chench** [comment]
The important question is: tabs or spaces?

**Comment by qasim** [comment]
@cchens: PEP8 recommends spaces, and to only use tabs when working with code that's already using tabs. SPACES > TABS!

**Comment by 1vn** [comment]
spaces

**Comment by g3chench** [comment]
@qasim 

> SPACES > TABS!

[Then what is this](https://github.com/cobalt-io/cobalt/commit/34a94aeebcb29d79f054fce7a358e412f02ad128)

**Comment by qasim** [comment]
@cchens: photoshopped.
